name: movie_booking_ticket
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.3.0
  flutter_native_splash: ^2.4.7
  bloc: ^9.2.1
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.3.0
  cached_network_image: ^3.4.1
  equatable: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  flutter_gen_runner: ^5.14.1

flutter_gen:
  output: lib/gen/ 
  line_length: 80

  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/nav_bar/
    - assets/images/profile_menu/
    - assets/images/general/
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700

